jokes = [
    "Why did the tomato turn red? Because it saw the curry in the kitchen!",
    "Why are Golgappas bad at relationships? They burst under pressure.",
    "What do you call an Indian city that always sleeps? Snooze-abad.",
    "Why dont South Indians trust ladders? They prefer dosa steps!",
    "Whats a Punjabis favorite vegetable? Sarson ka saag, because its full of balle balle!",
    "Why was the biryani late for the party? It was stuck in dum.",
    "Why dont Indians argue at weddings? Because they dont want to upset the laddu balance.",
    "Why did the chai cry? It got dumped by the biscuit.",
    "Whats a Gujaratis favorite plant? Methi, because its so dhokla-ble.",
    "Why did the coconut join the army? It wanted to be a hard nut to crack!",
    "Why do cricketers love curries? Because they always bowl you over.",
    "Whats a Delhiites favorite sport? Honking!",
    "Why are idlis so good at keeping secrets? Because theyre soft-spoken.",
    "What did the dosa say to the sambar? 'Youre my perfect dip-lomatic partner!'",
    "Why dont onions make good friends? They always make you cry!",
    "What do you call a Bollywood movie with no dancing? A flop kahani.",
    "Why did the Indian man bring a ladder to the bank? To reach the high-interest rates.",
    "Why was the paneer feeling sad? It wasnt grate-ful.",
    "Why dont Indians take escalators? Because they prefer to step up in life.",
    "Why did the chicken cross the Indian road? To escape the tandoor!",
    "What do you call a lazy naan? Naan-chalant.",
    "Why did the dosa break up with the chutney? It found sambar more spicy.",
    "Why did the samosa go to therapy? It was feeling a bit stuffed.",
    "Why was the roti feeling insecure? Because the naan always got more compliments.",
    "Whats a South Indian ghosts favorite snack? Bhootha-dosa!",
    "Why was the biryani always calm? Because it knew how to keep its layer intact.",
    "Whats a Punjabi astronauts favorite meal? Makki di roti and saag-in space!",
    "Why are Indians bad at hide-and-seek? Because the samosas always give them away.",
    "What do you call a dosa in a bad mood? A moody-roti.",
    "Why did the chutney blush? Because it was caught dipping into gossip.",
    "Whats a Bengalis favorite car brand? Mishti-bishi!",
    "Why do Gujaratis love going to the movies? They bring their own farsan!",
    "Why did the rasgulla break up with the jalebi? It couldnt handle the twists.",
    "Why are Indian weddings so loud? Because silence isnt part of the menu.",
    "Why did the paratha refuse to dance? It didnt want to roll away.",
    "What do you call a very polite samosa? A namaste-samosa.",
    "Why was the dosa always broke? It kept rolling in debt.",
    "Why did the chaiwala get a promotion? Because he was always brewing new ideas!",
    "What do you call a romantic biryani? One with a lot of spice and love.",
    "Why did the biscuit go to school? To become a smart-cookie!",
    "Whats a Hyderabadis favorite type of bread? Naan-stop.",
    "Why are Bollywood songs so addictive? Because theyre full of tune-tastic beats!",
    "Why dont dal and rice fight? Theyre the ultimate comfort couple.",
    "What do you call a dosa that went to space? A rocket dosa!",
    "Why did the jalebi get jealous? It saw the laddoo stealing all the limelight.",
    "Why did the pav bhaji go viral? Because it had all the right masala!",
    "Whats a North Indians favorite breakfast? Chhole-ek sandwich!",
    "Why did the butter chicken fail math? It couldnt figure out the naan-sense.",
    "Why dont Indian sweets do yoga? Because theyre already so flexible!",
    "Why was the chai so wise? It had steeped in knowledge for years.",
]