jokes = [
    "Why did the tomato turn red? Because it saw the curry in the kitchen!",
    "Why are Golgappas bad at relationships? They burst under pressure.",
    "What do you call an Indian city that always sleeps? Snooze-abad.",
    "Why dont South Indians trust ladders? They prefer dosa steps!",
    "Whats a Punjabis favorite vegetable? Sarson ka saag, because its full of balle balle!",
    "Why was the biryani late for the party? It was stuck in dum.",
    "Why dont Indians argue at weddings? Because they dont want to upset the laddu balance.",
    "Why did the chai cry? It got dumped by the biscuit.",
    "Whats a Gujaratis favorite plant? Methi, because its so dhokla-ble.",
    "Why did the coconut join the army? It wanted to be a hard nut to crack!",
    "Why do cricketers love curries? Because they always bowl you over.",
    "Whats a Delhiites favorite sport? Honking!",
    "Why are idlis so good at keeping secrets? Because theyre soft-spoken.",
    "What did the dosa say to the sambar? 'Youre my perfect dip-lomatic partner!'",
    "Why dont onions make good friends? They always make you cry!",
    "What do you call a Bollywood movie with no dancing? A flop kahani.",
    "Why did the Indian man bring a ladder to the bank? To reach the high-interest rates.",
    "Why was the paneer feeling sad? It wasnt grate-ful.",
    "Why dont Indians take escalators? Because they prefer to step up in life.",
    "Why did the chicken cross the Indian road? To escape the tandoor!",
    "What do you call a lazy naan? Naan-chalant.",
    "Why did the dosa break up with the chutney? It found sambar more spicy.",
    "Why did the samosa go to therapy? It was feeling a bit stuffed.",
    "Why was the roti feeling insecure? Because the naan always got more compliments.",
    "Whats a South Indian ghosts favorite snack? Bhootha-dosa!",
    "Why was the biryani always calm? Because it knew how to keep its layer intact.",
    "Whats a Punjabi astronauts favorite meal? Makki di roti and saag-in space!",
    "Why are Indians bad at hide-and-seek? Because the samosas always give them away.",
    "What do you call a dosa in a bad mood? A moody-roti.",
    "Why did the chutney blush? Because it was caught dipping into gossip.",
    "Whats a Bengalis favorite car brand? Mishti-bishi!",
    "Why do Gujaratis love going to the movies? They bring their own farsan!",
    "Why did the rasgulla break up with the jalebi? It couldnt handle the twists.",
    "Why are Indian weddings so loud? Because silence isnt part of the menu.",
    "Why did the paratha refuse to dance? It didnt want to roll away.",
    "What do you call a very polite samosa? A namaste-samosa.",
    "Why was the dosa always broke? It kept rolling in debt.",
    "Why did the chaiwala get a promotion? Because he was always brewing new ideas!",
    "What do you call a romantic biryani? One with a lot of spice and love.",
    "Why did the biscuit go to school? To become a smart-cookie!",
    "Whats a Hyderabadis favorite type of bread? Naan-stop.",
    "Why are Bollywood songs so addictive? Because theyre full of tune-tastic beats!",
    "Why dont dal and rice fight? Theyre the ultimate comfort couple.",
    "What do you call a dosa that went to space? A rocket dosa!",
    "Why did the jalebi get jealous? It saw the laddoo stealing all the limelight.",
    "Why did the pav bhaji go viral? Because it had all the right masala!",
    "Whats a North Indians favorite breakfast? Chhole-ek sandwich!",
    "Why did the butter chicken fail math? It couldnt figure out the naan-sense.",
    "Why dont Indian sweets do yoga? Because theyre already so flexible!",
    "Why was the chai so wise? It had steeped in knowledge for years.",
]

pickup_lines = [
    "Are you a samosa? Because you’ve got my heart wrapped up and fried to perfection.",
    "Are you made of masala? Because you just spiced up my life.",
    "Are you a gulab jamun? Because you’re the sweetest thing I’ve ever seen.",
    "Are you biryani? Because you’re dum-daar and irresistible.",
    "Are you a dosa? Because you’re flat-out amazing.",
    "Are you paneer? Because you make everything better.",
    "Do you have some chai? Because you’ve steeped into my heart.",
    "Are you butter chicken? Because you’ve got me feeling creamy inside.",
    "Are you a jalebi? Because you’re twisting my heart into knots.",
    "Are you a roti? Because my life feels incomplete without you.",
    "Are you mango pickle? Because you’re tangy, spicy, and unforgettable.",
    "Are you a Punjabi wedding? Because you’ve got me dancing inside.",
    "Are you an idli? Because you’ve risen perfectly in my life.",
    "Are you sambar? Because you add the perfect flavor to my world.",
    "Are you chai? Because I’d sip on your love all day long.",
    "Are you pav bhaji? Because my heart goes naan-stop for you.",
    "Are you rasmalai? Because you’re soft, sweet, and simply delightful.",
    "Are you from Hyderabad? Because you’ve got me biryani-ing for your love.",
    "Are you filter coffee? Because you’ve perked up my day.",
    "Are you a paratha? Because you’ve got so many layers to love.",
    "Are you sarson ka saag? Because you make my heart balle balle!",
    "Are you jal jeera? Because you’re refreshing and one-of-a-kind.",
    "Are you dal chawal? Because you’re my ultimate comfort zone.",
    "Are you mithai? Because life’s sweeter with you.",
    "Are you chai pakoras? Because you’re my perfect monsoon partner.",
    "Are you thandai? Because you’ve got me high on love.",
    "Are you golgappa water? Because you’ve got the perfect kick.",
    "Are you dosa batter? Because you’re the base of my happiness.",
    "Are you bhindi masala? Because you’re simple yet irresistible.",
    "Are you coconut chutney? Because you complement my every mood.",
    "Are you idiyappam? Because you’re woven into my heartstrings.",
    "Are you an Indian wedding song? Because you make my heart dhol-ed out.",
    "Are you aamras? Because you’re the mango of my dreams.",
    "Are you pulao? Because you bring color to my life.",
    "Are you tandoori? Because you’ve grilled your way into my soul.",
    "Are you paneer tikka? Because you’re grilled to perfection.",
    "Are you a laddoo? Because you’re round and sweet—just like love should be.",
    "Are you dal makhani? Because you’re rich and comforting.",
    "Are you poha? Because you’re light but unforgettable.",
    "Are you masala chai? Because you’ve got the perfect mix of spice and sweetness.",
    "Are you vada pav? Because you’re a classic in every sense.",
    "Are you khichdi? Because you bring warmth to my heart.",
    "Are you idli sambhar? Because you’re a balanced delight.",
    "Are you butter naan? Because you’ve got me melted and warm.",
    "Are you rasgulla? Because you’ve soaked up all my love.",
    "Are you paneer pakoda? Because you’ve got the crunch and the heart.",
    "Are you bhel puri? Because you’re a perfect mix of everything I love.",
    "Are you a dosa at a South Indian restaurant? Because you’re worth waiting for.",
]
